version: 2
updates:
  - package-ecosystem: npm
    directory: /cli
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /extensions/idd-core
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /packages/vscode-extension
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /packages/idd-ui-pwa
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly